# Use GitHub Pages-compatible theme and plugins
# Update 'url' and 'baseurl' after publishing

title: Best Buys & Price Advice
description: Free price comparison and buying advice to save you money on everyday purchases.
author: Your Name
email: you@example.com
url: ""   # e.g., https://your-username.github.io
baseurl: "" # e.g., /price-advice

# GitHub Pages supports these plugins natively
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

theme: minima

# Navigation (minima)
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/your-username" }

collections:
  guides:
    output: true
    permalink: /guides/:title/

# Defaults
defaults:
  - scope: { path: "" }
    values:
      layout: default
  - scope: { path: "_guides" }
    values:
      layout: post

# Build settings
markdown: kramdown
permalink: pretty

# Exclude
exclude:
  - README.md
  - .gitignore
